[theme]
base = "light"
primaryColor = "#0E5484"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F8FB"
textColor = "#1a1a1a"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
